[package]
name = "deer-book"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ex04"
path = "src/ex04.rs"

[dependencies]
proconio = "0.4.3"
